# Generated by Django 5.0.7 on 2024-07-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cdrValue',
        ),
        migrations.AddField(
            model_name='patient',
            name='caretakerId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
