# Generated by Django 5.0.7 on 2024-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('patientId', models.CharField(max_length=20)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
