# Generated by Django 5.0.7 on 2024-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_imagemodel_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='createDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
