# Generated by Django 5.0.7 on 2024-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_surveymodel_rename_id_patient_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='patientId',
            field=models.IntegerField(null=True),
        ),
    ]
