# Generated by Django 5.0.7 on 2024-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_surveymodel_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='cdrValues',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='community',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='hobbies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='judgment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='orientation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='personalCare',
            field=models.IntegerField(null=True),
        ),
    ]
