# Generated by Django 5.0.7 on 2024-07-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_surveymodel_cdrvalues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='patientId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
