# Generated by Django 5.0.7 on 2024-07-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_surveymodel_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='createDate',
            field=models.DateField(),
        ),
    ]
