# Generated by Django 5.0.7 on 2024-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_imagemodel_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='createDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
