# Generated by Django 5.0.7 on 2024-07-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_surveymodel_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='patientId',
            field=models.FloatField(null=True),
        ),
    ]
