# Generated by Django 5.0.7 on 2024-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_surveymodel_cdrvalues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cdrId',
            field=models.FloatField(null=True),
        ),
    ]
