# Generated by Django 5.0.7 on 2024-07-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_patient_cdrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cdrId',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
